version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_PASS}
      KC_HOSTNAME: keycloak
    command: start-dev
    depends_on:
      - postgres
    # network_mode: host
    networks:
      - keycloak-network

  postgres:
    image: postgres:13.2
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    expose:
      - 5432
    # network_mode: host
    networks:
      - keycloak-network

  app:
    image: golang:1.19rc2-alpine3.16
    container_name: app
    depends_on:
      - keycloak
    ports:
      - 8081:8081
    volumes:
      - ./keycloak:/usr/src/app
    command: go run /usr/src/app/client/main.go
    environment:
      CLIENT_SECRET: ${CLIENTSECRET}
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
    # network_mode: host
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
  host:
    driver: host